### ISSUE TITLE
I recive this message ...

### ISSUE THREAD

**Issue by ghost** [bazitur/brackets-python-tools#3]
![2018-01-31 08_22_50-includes_questions inc php 04_wahlding - brackets](https://user-images.githubusercontent.com/29942423/35609989-ff93c566-065f-11e8-8b4d-714344c736bb.jpg)

**Comment by bazitur** [comment]
Hello @daniloulf.
Could you please provide Brackets' console log?

**Comment by ghost** [comment]
`thirdparty.min.js:13 Less has finished and no sheets were loaded.
3/command/Menus.js:991 Error setting menu item shortcut: 1(anonymous function) @ /command/Menus.js:991
file:///C:/Users/danil/AppData/Roaming/Brackets/extensions/user/bigeyex.brackets-wordhint-1.0.2/main.js Failed to load resource: net::ERR_FILE_NOT_FOUND
/utils/ExtensionLoader.js:227 [Extension] failed to load C:/Users/danil/AppData/Roaming/Brackets/extensions/user/bigeyex.brackets-wordhint-1.0.2 - Module does not exist: file:///C:/Users/danil/AppData/Roaming/Brackets/extensions/user/bigeyex.brackets-wordhint-1.0.2/main.jserrback @ /utils/ExtensionLoader.js:227
/utils/ExtensionLoader.js:227 [Extension] failed to load C:/Users/danil/AppData/Roaming/Brackets/extensions/user/brackets-builder-extended-0.0.6 - Error: Module name "view/PanelManager" has not been loaded yet for context: _
http://requirejs.org/docs/errors.html#notloadederrback @ /utils/ExtensionLoader.js:227
/utils/ExtensionLoader.js:231 Error: Module name "view/PanelManager" has not been loaded yet for context: _
http://requirejs.org/docs/errors.html#notloaded
    at makeError (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:166:17)
    at Object.localRequire [as getModule] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1400:44)
    at Object.<anonymous> (file:///C:/Users/danil/AppData/Roaming/Brackets/extensions/user/brackets-builder-extended-0.0.6/main.js:21:40)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.<anonymous> (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1121:34)
    at file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:132:23
    at file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1164:21
    at each (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:57:31)
    at Object.Module.emit (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1163:17)
/utils/ExtensionLoader.js:227 [Extension] failed to load C:/Users/danil/AppData/Roaming/Brackets/extensions/user/Brackets-Build-Systems-master - Error: Module name "view/PanelManager" has not been loaded yet for context: _
http://requirejs.org/docs/errors.html#notloadederrback @ /utils/ExtensionLoader.js:227
/utils/ExtensionLoader.js:231 Error: Module name "view/PanelManager" has not been loaded yet for context: _
http://requirejs.org/docs/errors.html#notloaded
    at makeError (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:166:17)
    at Object.localRequire [as getModule] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1400:44)
    at Object.<anonymous> (file:///C:/Users/danil/AppData/Roaming/Brackets/extensions/user/Brackets-Build-Systems-master/modules/InfoPanel.js:4:32)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.<anonymous> (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1121:34)
    at file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:132:23
    at file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1164:21
    at each (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:57:31)
    at Object.Module.emit (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1163:17)
/utils/ExtensionLoader.js:227 [Extension] failed to load C:/Users/danil/AppData/Roaming/Brackets/extensions/user/brackets-python-tools-master - Error: Preference bazitur.python-tools.pathToPython was redefinederrback @ /utils/ExtensionLoader.js:227
/utils/ExtensionLoader.js:231 Error: Preference bazitur.python-tools.pathToPython was redefined
    at PreferencesSystem._.extend.definePreference (/preferences/PreferencesBase.js:1314:23)
    at Object.PrefixedPreferencesSystem.definePreference (/preferences/PreferencesBase.js:1081:30)
    at Object.<anonymous> (file:///C:/Users/danil/AppData/Roaming/Brackets/extensions/user/brackets-python-tools-master/main.js:79:17)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.<anonymous> (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1121:34)
    at file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:132:23
    at file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1164:21
    at each (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:57:31)
    at Object.Module.emit (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1163:17)
/filesystem/FileSystem.js:904 Failed to watch root:  Z:/01_mattick/04_wahlding/ NetworkDriveNotSupported
/project/ProjectManager.js:757 Error watching project root:  Z:/01_mattick/04_wahlding/ NetworkDriveNotSupported(anonymous function) @ /project/ProjectManager.js:757
/command/KeyBindingManager.js:578 Failed to normalize Cmd-Shift-]
/command/KeyBindingManager.js:578 Failed to normalize Cmd-Shift-[
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:84 NodeSocketTransport - start
/utils/DeprecationWarning.js:88 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:467:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:19:405)
    at addHandlers (file:///C:/Users/danil/AppData/Roaming/Brackets/extensions/user/toshsharma.bookmarks/main.js:204:9)
    at load (file:///C:/Users/danil/AppData/Roaming/Brackets/extensions/user/toshsharma.bookmarks/main.js:210:9)
    at file:///C:/Users/danil/AppData/Roaming/Brackets/extensions/user/toshsharma.bookmarks/main.js:216:9
    at _callHandler (/utils/AppInit.js:89:13)
    at Object._dispatchReady (/utils/AppInit.js:109:13)
    at Object.eval (/brackets.js:303:33)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:19:26911)
/utils/EventDispatcher.js:102 Registering for deprecated event 'currentDocumentChange'. Instead, use MainViewManager.currentFileChange. Error
    at Object.on (/utils/EventDispatcher.js:102:43)
    at addHandlers (file:///C:/Users/danil/AppData/Roaming/Brackets/extensions/user/toshsharma.bookmarks/main.js:204:28)
    at load (file:///C:/Users/danil/AppData/Roaming/Brackets/extensions/user/toshsharma.bookmarks/main.js:210:9)
    at file:///C:/Users/danil/AppData/Roaming/Brackets/extensions/user/toshsharma.bookmarks/main.js:216:9
    at _callHandler (/utils/AppInit.js:89:13)
    at Object._dispatchReady (/utils/AppInit.js:109:13)
    at Object.eval (/brackets.js:303:33)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:19:26911)
    at Object.k.add [as done] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:19:27220)
    at Object.d.always (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:19:28096)
/utils/NodeDomain.js:144 [NodeDomain] Error loading domain "python-tools": Unable to load one of the modules: C:/Users/danil/AppData/Roaming/Brackets/extensions/user/brackets-python-tools-master/node/PythonDomain, reason: Command python-tools.startShell already registered(anonymous function) @ /utils/NodeDomain.js:144
main.js:124 Critical error in Python Domain(anonymous function) @ main.js:124
main.js:125 This socket is closed(anonymous function) @ main.js:125
/utils/DeprecationWarning.js:88 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:467:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:19:405)
    at ColorsPP.init (file:///C:/Users/danil/AppData/Roaming/Brackets/extensions/user/kalimah-colors-plus-plus/main.js:962:13)
/command/Menus.js:660 _getRelativeMenuItem(): MenuItem with Command id ColorsPP.Options not found in the Menu edit-menu(anonymous function) @ /command/Menus.js:660`

sorry while I am late ...

**Comment by ghost** [comment]
Now it works, thank you. It was miss jedi and had some conflicts with other addons.
